name: Reusable Release

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - name: "api"
            context: "."
            dockerfile: "./apps/api/Dockerfile"
            image: "monorepo-api"
          - name: "web"
            context: "."
            dockerfile: "./apps/web/Dockerfile"
            image: "monorepo-web"
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ matrix.app.image }}
          tags: |
            type=ref,event=tag
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.app.context }}
          file: ${{ matrix.app.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
