name: Reusable Release Workflow

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [web, api] # add more apps here if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Docker Image
        run: |
          IMAGE_NAME=${{ matrix.app }}
          DOCKER_REPO=${{ inputs.registry }}/${{ secrets.DOCKER_USERNAME }}

          echo "Building image for $IMAGE_NAME"
          echo "Target registry: $DOCKER_REPO"
          echo "Environment: ${{ inputs.environment }}"

          docker buildx build \
            --platform linux/amd64 \
            -f ./apps/${IMAGE_NAME}/Dockerfile \
            -t ${DOCKER_REPO}/${IMAGE_NAME}:latest \
            -t ${DOCKER_REPO}/${IMAGE_NAME}:${{ github.sha }} \
            --push \
            .

          docker push $DOCKER_REPO/${IMAGE_NAME}:latest
          docker push $DOCKER_REPO/${IMAGE_NAME}:${{ github.sha }}
