name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    uses: ./.github/workflows/_release.yaml
    with:
      image-name: "monorepo-app"
      registry: "docker.io/stevehoober"
      environment: "production"
