name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    uses: ./.github/workflows/_release.yaml
    with:
      registry: "docker.io/stevehoober"
      environment: "production"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
